services:
  mysql:
    image: mysql:8.0 
    container_name: expenses_api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: expenses 
      MYSQL_DATABASE: expenses_db      
      MYSQL_USER: expenses              
      MYSQL_PASSWORD: expenses      
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql 
volumes:
  mysql_data: 
